version: "3.9"

services:
  redis:
    image: bitnami/redis:6.2
    ports:
      - "6379:6379"
    networks:
      - backend
    restart: on-failure
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
networks:
  backend:
    driver: bridge
