server:
  port: 1011

spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: redis
